name: docs

on: [push, workflow_dispatch, pull_request]

jobs:
  docs:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build index list
        working-directory: ${{ github.workspace }}/docs/user_peripherals
        run: |
          python3 script_index_list_build.py

      - name: Upload index_list.json as artifact
        uses: actions/upload-artifact@v4
        with:
          name: index_list.json  # Artifact name
          path: ${{ github.workspace }}/docs/user_peripherals/index_list.json  # Path and name of the file to be uploaded

      - name: Build docs
        uses: TinyTapeout/tt-gds-action/docs@ttsky25a
        with:
          tools-ref: ttsky25a


